name: DesafioStone

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build Docker
      run: docker build -t test -f DockerfileTest .
    - name: Run Docker
      run: docker run test
