name: DesafioStone

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build MySQL
      run: docker run --name db -p 3306 -e 'MYSQL_ROOT_PASSWORD=pass' -d mysql/mysql-server:latest

    - name: Build Docker
      run: docker build -t test -f DockerfileTest .
    - name: Run Docker
      run: docker run --link db -e 'ConnectionStrings__MySqlConnectionString=Server=localhost;DataBase=Copa;Uid=root;Pwd=pass' test
